# Generated by Django 3.1.4 on 2021-01-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_company_company_admin_user'),
        ('SuperPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_pay', models.CharField(blank=True, default='', max_length=100)),
                ('apple_pay', models.CharField(blank=True, default='', max_length=100)),
                ('paypal', models.CharField(blank=True, default='', max_length=100)),
                ('samsung_pay', models.CharField(blank=True, default='', max_length=100)),
                ('cash_app', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, default='', max_length=1000)),
                ('instagram', models.URLField(blank=True, default='', max_length=1000)),
                ('snapchat', models.URLField(blank=True, default='', max_length=1000)),
                ('linkedin', models.URLField(blank=True, default='', max_length=1000)),
                ('twitter', models.URLField(blank=True, default='', max_length=1000)),
                ('tumblr', models.URLField(blank=True, default='', max_length=1000)),
                ('dribble', models.URLField(blank=True, default='', max_length=1000)),
                ('behance', models.URLField(blank=True, default='', max_length=1000)),
                ('pinterest', models.URLField(blank=True, default='', max_length=1000)),
                ('youtube', models.URLField(blank=True, default='', max_length=1000)),
                ('telegram', models.URLField(blank=True, default='', max_length=1000)),
                ('reddit', models.URLField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SuperPanel.userextention')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pictures')),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=12)),
                ('telephone_number', models.CharField(blank=True, default='', max_length=12)),
                ('fax_number', models.CharField(blank=True, default='', max_length=12)),
                ('website', models.URLField(blank=True, default='', max_length=1000)),
                ('skype_id', models.CharField(blank=True, default='', max_length=100)),
                ('address1', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('zipcode', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('another_address1', models.CharField(blank=True, default='', max_length=100)),
                ('another_address2', models.CharField(blank=True, default='', max_length=100)),
                ('another_city', models.CharField(blank=True, default='', max_length=100)),
                ('another_state', models.CharField(blank=True, default='', max_length=100)),
                ('another_zipcode', models.CharField(blank=True, default='', max_length=100)),
                ('another_country', models.CharField(blank=True, default='', max_length=100)),
                ('email_address1', models.EmailField(blank=True, default='', max_length=12)),
                ('email_address2', models.EmailField(blank=True, default='', max_length=12)),
                ('email_address3', models.EmailField(blank=True, default='', max_length=12)),
                ('website1', models.URLField(blank=True, default='', max_length=1000)),
                ('website2', models.URLField(blank=True, default='', max_length=1000)),
                ('website3', models.URLField(blank=True, default='', max_length=1000)),
                ('mobile1', models.CharField(blank=True, default='', max_length=12)),
                ('mobile2', models.CharField(blank=True, default='', max_length=12)),
                ('mobile3', models.CharField(blank=True, default='', max_length=12)),
                ('profile_link', models.URLField(blank=True, default='', max_length=1000)),
                ('is_profile_link_active', models.BooleanField(default=False)),
                ('is_profile_status_active', models.BooleanField(default=False)),
                ('is_profile_editing_active', models.BooleanField(default=False)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('payment_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.paymentdetail')),
                ('third_party_connection_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.thirdpartconnection')),
            ],
        ),
    ]
