# Generated by Django 3.1.4 on 2021-01-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20210118_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_address1',
            field=models.EmailField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_address2',
            field=models.EmailField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_address3',
            field=models.EmailField(blank=True, default='', max_length=1000),
        ),
    ]
