# Generated by Django 3.1.4 on 2021-01-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtention',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('type', models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('COMPANY_ADMIN', 'COMPANY_ADMIN'), ('COMPANY_EMPLOYEE', 'COMPANY_EMPLOYEE'), ('COMMON_EMPLOYEE', 'COMMON_EMPLOYEE')], max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful_count', models.IntegerField(default=0)),
                ('unsuccessful_count', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, upload_to='employee_upload_file')),
                ('c_logo', models.FileField(blank=True, upload_to='company_logos')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
