# Generated by Django 3.1.4 on 2021-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
        ('SuperPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='users_list',
            field=models.ManyToManyField(blank=True, to='Employees.Employee'),
        ),
    ]
