# Generated by Django 3.1.4 on 2021-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperPanel', '0002_uploaddata_users_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
