# Generated by Django 3.1.4 on 2021-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperPanel', '0003_auto_20210118_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextention',
            name='resetToken',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
