# Generated by Django 3.1.4 on 2021-01-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('SuperPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperPanel.userextention'),
        ),
    ]
